# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ats-bridge', ['core'])
    module.source = [
        'model/ats-bridge.cc',
        'helper/ats-bridge-helper.cc',
        'model/ats-transmission-queue-disc.cc',
        'model/ats-scheduler-queue-disc.cc',
        'model/ats-scheduler-group.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ats-bridge')
    module_test.source = [
        'test/ats-bridge-test-suite.cc',
        'test/ats-queue-disc-test-suice.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ats-bridge'
    headers.source = [
        'model/ats-bridge.h',
        'helper/ats-bridge-helper.h',
        'model/ats-transmission-queue-disc.h',
        'model/ats-scheduler-queue-disc.h',
        'model/ats-scheduler-group.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

