# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ats-bridge-example', ['ats-bridge', 'applications', 'internet', 'csma','clock'])
    obj.source = 'ats-bridge-example.cc'

